# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sHr2kk198GkVkMmqr13dBoKIvSsDA_s
"""

# -*- coding: utf-8 -*-



import os
from datetime import datetime

import pandas as pd
import gradio as gr
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from fpdf import FPDF


# ============================================================
# CONFIGURATION
# ============================================================

APP_TITLE = "🧠 AI Antibiotic Misuse Detector (Next-Gen)"

USERS_FILE = "users.csv"
PRESCRIPTIONS_FILE = "prescriptions.csv"
LOG_FILE = "aamd_logs.csv"


# ============================================================
# CREATE DEFAULT DATA FILES
# ============================================================

def create_default_files():

    # -----------------------------
    # prescriptions.csv
    # -----------------------------

    if not os.path.exists(PRESCRIPTIONS_FILE):

        prescriptions_data = [
            [5, 20, 0, 1, "viral infection", "none"],
            [12, 25, 1, 1, "pneumonia", "amoxicillin"],
            [7, 50, 0, 1, "viral infection", "azithromycin"],
            [30, 15, 0, 0, "bacterial gastroenteritis", "none"],
            [8, 18, 1, 1, "pneumonia", "none"],
            [15, 22, 0, 0, "viral infection", "none"],
            [6, 45, 1, 1, "viral infection", "amoxicillin"],
            [10, 20, 0, 0, "pneumonia", "azithromycin"],
            [25, 15, 0, 1, "bacterial infection", "amoxicillin"],
            [40, 10, 0, 0, "viral infection", "none"]
        ]

        prescriptions_df = pd.DataFrame(
            prescriptions_data,
            columns=[
                "age",
                "dose_mg_per_kg",
                "prior_abx_30d",
                "fever_flag",
                "diagnosis_text",
                "meds"
            ]
        )

        prescriptions_df.to_csv(
            PRESCRIPTIONS_FILE,
            index=False
        )

        print("✅ prescriptions.csv created")


    # -----------------------------
    # users.csv
    # -----------------------------

    if not os.path.exists(USERS_FILE):

        users_data = [
            [
                "doctor1",
                "doctor1@example.com",
                "doc123",
                "Doctor"
            ],
            [
                "pharma1",
                "pharma1@example.com",
                "pharmacist123",
                "Pharmacist"
            ],
            [
                "admin",
                "admin@example.com",
                "admin123",
                "Admin"
            ]
        ]

        users_df = pd.DataFrame(
            users_data,
            columns=[
                "username",
                "email",
                "password",
                "role"
            ]
        )

        users_df.to_csv(
            USERS_FILE,
            index=False
        )

        print("✅ users.csv created")


create_default_files()


# ============================================================
# LOAD DATA
# ============================================================

df = pd.read_csv(PRESCRIPTIONS_FILE)


# ============================================================
# CLEAN DATA
# ============================================================

required_columns = [
    "age",
    "dose_mg_per_kg",
    "prior_abx_30d",
    "fever_flag",
    "diagnosis_text",
    "meds"
]

for column in required_columns:

    if column not in df.columns:

        if column == "diagnosis_text":
            df[column] = ""

        elif column == "meds":
            df[column] = "none"

        else:
            df[column] = 0


df["age"] = pd.to_numeric(
    df["age"],
    errors="coerce"
).fillna(0)

df["dose_mg_per_kg"] = pd.to_numeric(
    df["dose_mg_per_kg"],
    errors="coerce"
).fillna(0)

df["prior_abx_30d"] = pd.to_numeric(
    df["prior_abx_30d"],
    errors="coerce"
).fillna(0)

df["fever_flag"] = pd.to_numeric(
    df["fever_flag"],
    errors="coerce"
).fillna(0)

df["diagnosis_text"] = (
    df["diagnosis_text"]
    .fillna("")
    .astype(str)
)

df["meds"] = (
    df["meds"]
    .fillna("none")
    .astype(str)
)


# ============================================================
# RULE-BASED MISUSE DETECTION
# ============================================================

def detect_misuse(row):

    diagnosis = str(
        row["diagnosis_text"]
    ).lower()

    medication = str(
        row["meds"]
    ).lower()

    dose = float(
        row["dose_mg_per_kg"]
    )

    # Antibiotic with likely viral infection
    if "viral" in diagnosis and medication not in [
        "none",
        "",
        "na",
        "no"
    ]:
        return 1

    # No antibiotic recorded for pneumonia
    if "pneumonia" in diagnosis and medication in [
        "none",
        "",
        "na",
        "no"
    ]:
        return 1

    # Prototype high-dose threshold
    if dose > 40:
        return 1

    return 0


df["misuse_flag"] = df.apply(
    detect_misuse,
    axis=1
)


# ============================================================
# MACHINE LEARNING MODEL
# ============================================================

FEATURE_COLUMNS = [
    "age",
    "dose_mg_per_kg",
    "prior_abx_30d",
    "fever_flag"
]

X = df[FEATURE_COLUMNS]
y = df["misuse_flag"]


model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

model.fit(X, y)


# ============================================================
# SESSION
# ============================================================

SESSION = {
    "authenticated": False,
    "username": None,
    "role": None
}


# ============================================================
# AUTHENTICATION
# ============================================================

def signup(
    username,
    email,
    password,
    role
):

    if not username or not email or not password or not role:
        return "❌ Please fill all fields."

    users = pd.read_csv(
        USERS_FILE
    )

    if username in users["username"].astype(str).values:

        return "❌ Username already exists."

    new_user = pd.DataFrame(
        [[
            username,
            email,
            password,
            role
        ]],
        columns=[
            "username",
            "email",
            "password",
            "role"
        ]
    )

    users = pd.concat(
        [
            users,
            new_user
        ],
        ignore_index=True
    )

    users.to_csv(
        USERS_FILE,
        index=False
    )

    return (
        f"✅ Account created successfully for "
        f"**{username}** ({role})."
    )


def login(
    username,
    password
):

    if not username or not password:

        return (
            gr.Group(visible=True),
            gr.Group(visible=False),
            "❌ Enter username and password."
        )

    users = pd.read_csv(
        USERS_FILE
    )

    users["username"] = users[
        "username"
    ].astype(str)

    users["password"] = users[
        "password"
    ].astype(str)

    match = users[
        (users["username"] == str(username))
        &
        (users["password"] == str(password))
    ]

    if match.empty:

        return (
            gr.Group(visible=True),
            gr.Group(visible=False),
            "❌ Invalid username or password."
        )

    role = str(
        match.iloc[0]["role"]
    )

    SESSION["authenticated"] = True
    SESSION["username"] = str(username)
    SESSION["role"] = role

    return (
        gr.Group(visible=False),
        gr.Group(visible=True),
        f"✅ Welcome **{username}**! Role: **{role}**"
    )


def logout():

    SESSION["authenticated"] = False
    SESSION["username"] = None
    SESSION["role"] = None

    return (
        gr.Group(visible=True),
        gr.Group(visible=False),
        "👋 Logged out successfully."
    )


# ============================================================
# PREDICTION
# ============================================================

def predict_misuse(
    age,
    dose,
    prior_abx,
    fever,
    diagnosis_text,
    meds,
    ui_lang
):

    try:

        age = float(age or 0)
        dose = float(dose or 0)
        prior_abx = int(prior_abx or 0)
        fever = int(fever or 0)

    except Exception:

        return "❌ Please enter valid numeric values."


    diagnosis_text = str(
        diagnosis_text or ""
    ).strip()

    meds = str(
        meds or "none"
    ).strip()

    diagnosis_lower = diagnosis_text.lower()
    meds_lower = meds.lower()


    misuse_type = ""


    # ---------------------------------
    # Rule 1
    # ---------------------------------

    if (
        "viral" in diagnosis_lower
        and meds_lower not in [
            "none",
            "",
            "na",
            "no"
        ]
    ):

        misuse_type = (
            "Antibiotic recorded for a likely "
            "viral infection."
        )


    # ---------------------------------
    # Rule 2
    # ---------------------------------

    elif (
        "pneumonia" in diagnosis_lower
        and meds_lower in [
            "none",
            "",
            "na",
            "no"
        ]
    ):

        misuse_type = (
            "No antibiotic is recorded for "
            "a pneumonia case."
        )


    # ---------------------------------
    # Rule 3
    # ---------------------------------

    elif dose > 40:

        misuse_type = (
            "Dose exceeds the prototype's "
            "configured safety threshold."
        )


    # ---------------------------------
    # ML
    # ---------------------------------

    else:

        input_data = pd.DataFrame(
            [[
                age,
                dose,
                prior_abx,
                fever
            ]],
            columns=FEATURE_COLUMNS
        )

        prediction = model.predict(
            input_data
        )[0]

        if prediction == 1:

            misuse_type = (
                "Potential antibiotic misuse "
                "detected by the ML model."
            )

        else:

            misuse_type = (
                "No misuse pattern detected "
                "by the prototype."
            )


    # ========================================================
    # RESULT
    # ========================================================

    is_misuse = (
        "No misuse pattern" not in misuse_type
    )


    if ui_lang == "Hindi":

        if is_misuse:

            result_title = "⚠️ संभावित दुरुपयोग पाया गया"

            recommendation = (
                "प्रिस्क्रिप्शन की चिकित्सकीय समीक्षा करें "
                "और स्थानीय अस्पताल/क्लिनिकल प्रोटोकॉल "
                "का पालन करें।"
            )

        else:

            result_title = "✅ कोई स्पष्ट दुरुपयोग पैटर्न नहीं"

            recommendation = (
                "इस प्रोटोटाइप के अनुसार कोई स्पष्ट "
                "दुरुपयोग पैटर्न नहीं मिला। अंतिम निर्णय "
                "योग्य चिकित्सक द्वारा किया जाना चाहिए।"
            )

    else:

        if is_misuse:

            result_title = (
                "⚠️ Potential Misuse Detected"
            )

            recommendation = (
                "Review the prescription clinically "
                "and follow applicable hospital or "
                "clinical guidelines."
            )

        else:

            result_title = (
                "✅ No Clear Misuse Pattern"
            )

            recommendation = (
                "No clear misuse pattern was detected "
                "by this prototype. Final clinical decisions "
                "must be made by a qualified healthcare professional."
            )


    result = f"""
### {result_title}

**Reason:**
{misuse_type}

**Recommendation:**
{recommendation}

---

⚠️ **Important:** This system is a research/educational prototype and must not replace professional medical judgment.
"""


    # ========================================================
    # SAVE LOG
    # ========================================================

    log_entry = pd.DataFrame(
        [{
            "timestamp":
                datetime.now().strftime(
                    "%Y-%m-%d %H:%M:%S"
                ),

            "user":
                SESSION.get("username"),

            "role":
                SESSION.get("role"),

            "age":
                age,

            "dose_mg_per_kg":
                dose,

            "prior_abx_30d":
                prior_abx,

            "fever_flag":
                fever,

            "diagnosis_text":
                diagnosis_text,

            "meds":
                meds,

            "prediction":
                result_title,

            "reason":
                misuse_type
        }]
    )


    if os.path.exists(LOG_FILE):

        log_entry.to_csv(
            LOG_FILE,
            mode="a",
            header=False,
            index=False
        )

    else:

        log_entry.to_csv(
            LOG_FILE,
            index=False
        )


    return result


# ============================================================
# PDF REPORT
# ============================================================

def generate_pdf(
    patient_name,
    age,
    dose,
    diagnosis,
    meds,
    result
):

    patient_name = str(
        patient_name or "Patient"
    )

    filename = (
        patient_name
        .replace(" ", "_")
        .replace("/", "_")
        + "_AAMD_Report.pdf"
    )


    pdf = FPDF()

    pdf.add_page()

    pdf.set_title(
        "AI Antibiotic Misuse Detector Report"
    )

    pdf.set_font(
        "Arial",
        "B",
        18
    )

    pdf.cell(
        0,
        12,
        "AI Antibiotic Misuse Detector",
        ln=True,
        align="C"
    )

    pdf.set_font(
        "Arial",
        "",
        11
    )

    pdf.cell(
        0,
        8,
        "Patient Prescription Analysis Report",
        ln=True,
        align="C"
    )

    pdf.ln(10)


    pdf.set_font(
        "Arial",
        "B",
        12
    )

    pdf.cell(
        0,
        8,
        "Patient Information",
        ln=True
    )

    pdf.set_font(
        "Arial",
        "",
        11
    )

    pdf.cell(
        0,
        8,
        f"Name: {patient_name}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Age: {age}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Dose entered: {dose} mg/kg",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Diagnosis: {diagnosis}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Prescribed antibiotic: {meds}",
        ln=True
    )

    pdf.ln(8)


    pdf.set_font(
        "Arial",
        "B",
        12
    )

    pdf.cell(
        0,
        8,
        "AI Analysis",
        ln=True
    )

    pdf.set_font(
        "Arial",
        "",
        10
    )


    # Remove markdown symbols for PDF
    clean_result = (
        str(result)
        .replace("**", "")
        .replace("###", "")
        .replace("⚠️", "")
        .replace("✅", "")
        .replace("🚨", "")
    )


    pdf.multi_cell(
        0,
        7,
        clean_result
    )


    pdf.ln(8)

    pdf.set_font(
        "Arial",
        "I",
        9
    )

    pdf.multi_cell(
        0,
        6,
        "Disclaimer: This is a research/educational "
        "prototype and is not a substitute for professional "
        "medical diagnosis, prescription, or treatment."
    )


    pdf.output(
        filename
    )

    return filename


# ============================================================
# DASHBOARD
# ============================================================

def dashboard():

    if not os.path.exists(LOG_FILE):

        return (
            "### Dashboard Summary\n\n"
            "No prediction data available yet.",
            None,
            pd.DataFrame()
        )


    logs = pd.read_csv(
        LOG_FILE
    )


    if logs.empty:

        return (
            "### Dashboard Summary\n\n"
            "No prediction data available yet.",
            None,
            logs
        )


    total = len(logs)


    if "prediction" in logs.columns:

        misuse_count = logs[
            "prediction"
        ].astype(str).str.contains(
            "Misuse",
            case=False,
            na=False
        ).sum()

    else:

        misuse_count = 0


    misuse_rate = round(
        (misuse_count / total) * 100,
        2
    )


    # ========================================================
    # CHART
    # ========================================================

    chart_path = "misuse_chart.png"


    plt.figure(
        figsize=(6, 4)
    )


    proper_count = total - misuse_count


    labels = [
        "Potential Misuse",
        "No Clear Misuse"
    ]

    values = [
        misuse_count,
        proper_count
    ]


    plt.pie(
        values,
        labels=labels,
        autopct="%1.1f%%"
    )

    plt.title(
        "Prescription Analysis"
    )

    plt.tight_layout()

    plt.savefig(
        chart_path
    )

    plt.close()


    summary = f"""
## 📊 Dashboard Summary

**Total Predictions:** {total}

**Potential Misuse Cases:** {misuse_count}

**No Clear Misuse Cases:** {proper_count}

**Potential Misuse Rate:** {misuse_rate}%

> This dashboard shows prototype analysis results and should not be treated as clinical statistics.
"""


    return (
        summary,
        chart_path,
        logs
    )


# ============================================================
# DOWNLOAD LOGS
# ============================================================

def download_logs():

    if os.path.exists(LOG_FILE):

        return LOG_FILE

    return None


# ============================================================
# CHATBOT
# ============================================================

def chatbot(
    message,
    ui_lang="English"
):

    message = str(
        message or ""
    )

    msg = message.lower()


    if "antibiotic" in msg and "viral" in msg:

        if ui_lang == "Hindi":

            return (
                "वायरल संक्रमण में एंटीबायोटिक का उपयोग "
                "आमतौर पर उचित नहीं होता। चिकित्सकीय सलाह "
                "और उचित जांच का पालन करें।"
            )

        return (
            "Antibiotics generally do not treat viral "
            "infections. Follow professional medical "
            "advice and appropriate evaluation."
        )


    if (
        "dose" in msg
        or "dosage" in msg
        or "mg/kg" in msg
    ):

        if ui_lang == "Hindi":

            return (
                "खुराक मरीज की उम्र, वजन, संक्रमण, "
                "दवा और अन्य clinical factors पर निर्भर "
                "करती है। निर्धारित खुराक के लिए योग्य "
                "चिकित्सक से सलाह लें।"
            )

        return (
            "Antibiotic dosage depends on the patient's "
            "age, weight, infection, medication and other "
            "clinical factors. Consult a qualified clinician "
            "for the prescribed dose."
        )


    if "pneumonia" in msg:

        if ui_lang == "Hindi":

            return (
                "निमोनिया में उचित diagnosis और treatment "
                "के लिए qualified healthcare professional "
                "की clinical evaluation जरूरी है।"
            )

        return (
            "Pneumonia requires appropriate clinical "
            "evaluation and treatment by a qualified "
            "healthcare professional."
        )


    if (
        "fever" in msg
        or "bukhar" in msg
    ):

        if ui_lang == "Hindi":

            return (
                "बुखार के कारण अलग-अलग हो सकते हैं। "
                "यदि बुखार गंभीर, लगातार या अन्य गंभीर "
                "लक्षणों के साथ है तो चिकित्सकीय सहायता लें।"
            )

        return (
            "Fever can have many causes. Seek professional "
            "medical evaluation if it is severe, persistent, "
            "or accompanied by concerning symptoms."
        )


    if (
        "help" in msg
        or "guide" in msg
    ):

        if ui_lang == "Hindi":

            return (
                "आप antibiotic misuse, prescription analysis, "
                "basic symptoms या system features के बारे "
                "में पूछ सकते हैं।"
            )

        return (
            "You can ask about antibiotic misuse, "
            "prescription analysis, basic symptoms, "
            "or system features."
        )


    if ui_lang == "Hindi":

        return (
            "मैं antibiotic misuse, prescription analysis "
            "और basic symptoms से संबंधित सामान्य guidance "
            "दे सकता हूँ।"
        )


    return (
        "I can provide general guidance about antibiotic "
        "misuse, prescription analysis and basic symptoms."
    )


# ============================================================
# GRADIO APPLICATION
# ============================================================

with gr.Blocks(
    title="AAMD Next-Gen"
) as app:

    # ========================================================
    # HEADER
    # ========================================================

    gr.Markdown(
        "# 🧠 AI Antibiotic Misuse Detector (Next-Gen)"
    )

    gr.Markdown(
        "Secure • Multi-Language • AI Prediction • "
        "Dashboard • Chatbot • Reports"
    )


    # ========================================================
    # AUTH PAGE
    # ========================================================

    with gr.Group(
        visible=True
    ) as auth_page:

        gr.Markdown(
            "## 🔐 User Authentication"
        )


        with gr.Tabs():

            # -------------------------
            # LOGIN
            # -------------------------

            with gr.Tab(
                "Login"
            ):

                login_user = gr.Textbox(
                    label="Username",
                    placeholder="Enter username"
                )

                login_pass = gr.Textbox(
                    label="Password",
                    type="password",
                    placeholder="Enter password"
                )

                login_btn = gr.Button(
                    "🔐 Login",
                    variant="primary"
                )

                login_msg = gr.Markdown()


            # -------------------------
            # SIGNUP
            # -------------------------

            with gr.Tab(
                "Signup"
            ):

                signup_user = gr.Textbox(
                    label="Username"
                )

                signup_email = gr.Textbox(
                    label="Email"
                )

                signup_pass = gr.Textbox(
                    label="Password",
                    type="password"
                )

                signup_role = gr.Dropdown(
                    [
                        "Doctor",
                        "Pharmacist",
                        "Admin"
                    ],
                    label="Role"
                )

                signup_btn = gr.Button(
                    "📝 Create Account"
                )

                signup_msg = gr.Markdown()


    # ========================================================
    # MAIN APPLICATION
    # ========================================================

    with gr.Group(
        visible=False
    ) as main_app:

        gr.Markdown(
            "## 👋 Welcome to AAMD Next-Gen System"
        )


        logout_btn = gr.Button(
            "🚪 Logout"
        )


        # ====================================================
        # TABS
        # ====================================================

        with gr.Tabs():


            # =================================================
            # PREDICTION
            # =================================================

            with gr.Tab(
                "🔍 Prediction"
            ):

                gr.Markdown(
                    "### Prescription Analysis"
                )


                patient_name = gr.Textbox(
                    label="Patient Name",
                    placeholder="Enter patient name"
                )


                age = gr.Number(
                    label="Patient Age",
                    minimum=0
                )


                dose = gr.Number(
                    label="Antibiotic Dose (mg/kg)",
                    minimum=0
                )


                prior_abx = gr.Radio(
                    [0, 1],
                    label="Prior Antibiotic Use (0=No, 1=Yes)",
                    value=0
                )


                fever = gr.Radio(
                    [0, 1],
                    label="Fever Present (0=No, 1=Yes)",
                    value=0
                )


                diagnosis = gr.Textbox(
                    label="Diagnosis",
                    placeholder="Example: viral infection"
                )


                meds = gr.Textbox(
                    label="Prescribed Antibiotic",
                    placeholder="Example: amoxicillin or none"
                )


                lang = gr.Dropdown(
                    [
                        "English",
                        "Hindi"
                    ],
                    label="Language",
                    value="English"
                )


                predict_btn = gr.Button(
                    "🔎 Predict & Recommend",
                    variant="primary"
                )


                prediction_output = gr.Markdown()


                predict_btn.click(
                    predict_misuse,
                    inputs=[
                        age,
                        dose,
                        prior_abx,
                        fever,
                        diagnosis,
                        meds,
                        lang
                    ],
                    outputs=prediction_output
                )


                # -------------------------------
                # PDF
                # -------------------------------

                gr.Markdown(
                    "### 📄 Generate Report"
                )


                pdf_btn = gr.Button(
                    "📄 Generate PDF Report"
                )


                pdf_output = gr.File(
                    label="Download PDF"
                )


                pdf_btn.click(
                    generate_pdf,
                    inputs=[
                        patient_name,
                        age,
                        dose,
                        diagnosis,
                        meds,
                        prediction_output
                    ],
                    outputs=pdf_output
                )


            # =================================================
            # DASHBOARD
            # =================================================

            with gr.Tab(
                "📊 Dashboard"
            ):

                gr.Markdown(
                    "### Prescription Analysis Dashboard"
                )


                refresh_btn = gr.Button(
                    "🔄 Refresh Dashboard"
                )


                summary = gr.Markdown()


                chart = gr.Image(
                    label="Misuse Analysis Chart",
                    type="filepath"
                )


                table = gr.Dataframe(
                    label="Prediction Logs",
                    interactive=False
                )


                refresh_btn.click(
                    dashboard,
                    inputs=None,
                    outputs=[
                        summary,
                        chart,
                        table
                    ]
                )


            # =================================================
            # CHATBOT
            # =================================================

            with gr.Tab(
                "💬 Chatbot"
            ):

                gr.Markdown(
                    "### 🩺 AAMD General Guidance Chatbot"
                )


                chatbot_lang = gr.Dropdown(
                    [
                        "English",
                        "Hindi"
                    ],
                    label="Language",
                    value="English"
                )


                chatbot_input = gr.Textbox(
                    label="Ask your question",
                    placeholder=(
                        "Example: What is antibiotic misuse?"
                    )
                )


                chatbot_btn = gr.Button(
                    "💬 Send",
                    variant="primary"
                )


                chatbot_output = gr.Markdown()


                chatbot_btn.click(
                    chatbot,
                    inputs=[
                        chatbot_input,
                        chatbot_lang
                    ],
                    outputs=chatbot_output
                )


            # =================================================
            # LOGS
            # =================================================

            with gr.Tab(
                "📥 Logs"
            ):

                gr.Markdown(
                    "### Download Prediction Logs"
                )


                download_btn = gr.Button(
                    "📥 Download CSV"
                )


                download_file = gr.File(
                    label="AAMD Logs"
                )


                download_btn.click(
                    download_logs,
                    inputs=None,
                    outputs=download_file
                )


    # ========================================================
    # AUTH EVENTS
    # ========================================================

    login_btn.click(
        login,
        inputs=[
            login_user,
            login_pass
        ],
        outputs=[
            auth_page,
            main_app,
            login_msg
        ]
    )


    logout_btn.click(
        logout,
        inputs=None,
        outputs=[
            auth_page,
            main_app,
            login_msg
        ]
    )


    signup_btn.click(
        signup,
        inputs=[
            signup_user,
            signup_email,
            signup_pass,
            signup_role
        ],
        outputs=signup_msg
    )


# ============================================================
# RENDER / PRODUCTION LAUNCH
# ============================================================

if __name__ == "__main__":

    port = int(
        os.environ.get(
            "PORT",
            "7860"
        )
    )

    print(
        f"🚀 Starting AAMD on port {port}"
    )

    app.launch(
        server_name="0.0.0.0",
        server_port=port,
        show_error=True
    )

