# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQ5uWEOoPao4TqoBiMqBDvqwpRCNXEti
"""



import pandas as pd

def build_features(df: pd.DataFrame):
    X = pd.DataFrame()
    X['age'] = df['age']
    X['prior_abx_30d'] = df['prior_abx_30d']
    X['fever_flag'] = df['fever_flag']
    X['is_child'] = (df['age'] < 18).astype(int)
    X['has_antibiotic'] = df['meds'].apply(lambda x: 0 if x.lower() in ['none', ''] else 1)
    X['common_cold'] = df['diagnosis_text'].apply(lambda x: 1 if 'cold' in x.lower() else 0)
    return X

def rule_check(record):
    flags = []
    diag = record.get('diagnosis_text', '').lower()
    meds = record.get('meds', '').lower()
    fever = record.get('fever_flag', 0)
    age = record.get('age', 0)
    dose = record.get('dose_mg_per_kg', 0)

    # Rule 1: Antibiotic for viral infection (common cold)
    if 'cold' in diag and meds != 'none' and fever == 0:
        flags.append("Antibiotic given for likely viral infection")
    # Rule 2: Missing pediatric dose
    if age < 18 and dose == 0:
        flags.append("Missing pediatric dose for child")

    return flags



# aamd_project/preprocessing/features.py
import pandas as pd

def build_features(df: pd.DataFrame):
    """
    Build simple tabular features used by the prototype model.
    Expect df columns: age, diagnosis_text, meds, dose_mg_per_kg, prior_abx_30d, fever_flag
    """
    X = pd.DataFrame()
    X['age'] = df['age'].astype(float)
    X['prior_abx_30d'] = df.get('prior_abx_30d', pd.Series([0]*len(df))).astype(float)
    X['fever_flag'] = df.get('fever_flag', pd.Series([0]*len(df))).astype(float)
    X['is_child'] = (X['age'] < 18).astype(int)

    # Does the record include any antibiotic?
    def has_antibiotic(meds):
        if pd.isna(meds): return 0
        s = str(meds).lower()
        if s.strip() in ('', 'none', 'na', 'no'): return 0
        return 1
    X['has_antibiotic'] = df['meds'].apply(has_antibiotic)

    # Simple diagnosis flags
    def diag_common_cold(text):
        if pd.isna(text): return 0
        return 1 if 'cold' in str(text).lower() else 0
    X['diag_common_cold'] = df['diagnosis_text'].apply(diag_common_cold)

    # dose mg/kg numeric
    X['dose_mg_per_kg'] = df.get('dose_mg_per_kg', pd.Series([0]*len(df))).fillna(0).astype(float)

    return X

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

df = pd.read_csv("prescriptions.csv")
print("✅ Dataset loaded successfully!\n")
print(df.head())

def detect_misuse(row):
    # Rule 1: Antibiotic prescribed for viral infection
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1  # misuse

    # Rule 2: No antibiotic but bacterial infection
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1

    # Rule 3: Overdose detection
    if row["dose_mg_per_kg"] > 40:
        return 1

    # Otherwise, assume appropriate
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)
print("\n✅ Misuse flag added successfully!")
print(df[["diagnosis_text", "meds", "dose_mg_per_kg", "misuse_flag"]].head())

X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
print("\n✅ Model trained successfully!")

y_pred = model.predict(X_test)
print("\n📊 Model Performance:\n")
print(classification_report(y_test, y_pred))

new_case = pd.DataFrame({
    "age": [10],
    "dose_mg_per_kg": [45],
    "prior_abx_30d": [1],
    "fever_flag": [0]
})

prediction = model.predict(new_case)[0]
print("\n🩺 Prediction for new case:", "⚠️ Misuse" if prediction == 1 else "✅ Appropriate use")



import gradio as gr
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# ----------------------------
# STEP 1: Load the CSV
# ----------------------------
df = pd.read_csv("prescriptions.csv")

# ----------------------------
# STEP 2: Rule-based misuse flag
# ----------------------------
def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

# ----------------------------
# STEP 3: Train the AI model
# ----------------------------
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 4: Define prediction function
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    # Rule-based logic (quick decision)
    if "viral" in diagnosis_text.lower() and meds != "none":
        return "⚠️ Misuse: Antibiotic for viral infection"
    if "pneumonia" in diagnosis_text.lower() and meds == "none":
        return "⚠️ Misuse: Missing antibiotic for bacterial infection"
    if dose > 40:
        return "⚠️ Misuse: Overdose detected"

    # AI model-based prediction
    data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                        columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
    pred = model.predict(data)[0]

    return "⚠️ Misuse detected" if pred == 1 else "✅ Appropriate Use"

# ----------------------------
# STEP 5: Build Gradio interface
# ----------------------------
app = gr.Interface(
    fn=predict_misuse,
    inputs=[
        gr.Number(label="Patient Age"),
        gr.Number(label="Antibiotic Dose (mg/kg)"),
        gr.Radio([0, 1], label="Prior Antibiotic Use (0=No, 1=Yes)"),
        gr.Radio([0, 1], label="Fever Present (0=No, 1=Yes)"),
        gr.Textbox(label="Diagnosis Text"),
        gr.Textbox(label="Prescribed Antibiotic (e.g., amoxicillin, none)")
    ],
    outputs=gr.Textbox(label="Prediction Result"),
    title="🧠 AI Antibiotic Misuse Detector (AAMD)",
    description="Enter patient info and prescription details to check if the antibiotic use is appropriate.",
    theme="soft"
)

# ----------------------------
# STEP 6: Launch the app
# ----------------------------



# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

# ----------------------------
# STEP 2: Rule-based misuse flag
# ----------------------------
def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

# ----------------------------
# STEP 3: Train AI model
# ----------------------------
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 4: Prediction function
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    # Rule-based detection
    if "viral" in diagnosis_text.lower() and meds != "none":
        result = "⚠️ Misuse: Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds == "none":
        result = "⚠️ Misuse: Missing antibiotic for bacterial infection"
    elif dose > 40:
        result = "⚠️ Misuse: Overdose detected"
    else:
        # AI prediction
        data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                            columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
        pred = model.predict(data)[0]
        result = "⚠️ Misuse detected" if pred == 1 else "✅ Appropriate Use"

    # ----------------------------
    # STEP 5: Log to CSV
    # ----------------------------
    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])

    # Append or create new file
    log_file = "aamd_logs.csv"
    if os.path.exists(log_file):
        log_entry.to_csv(log_file, mode="a", header=False, index=False)
    else:
        log_entry.to_csv(log_file, index=False)

    return result

# ----------------------------
# STEP 6: Gradio interface
# ----------------------------
app = gr.Interface(
    fn=predict_misuse,
    inputs=[
        gr.Number(label="Patient Age"),
        gr.Number(label="Antibiotic Dose (mg/kg)"),
        gr.Radio([0, 1], label="Prior Antibiotic Use (0=No, 1=Yes)"),
        gr.Radio([0, 1], label="Fever Present (0=No, 1=Yes)"),
        gr.Textbox(label="Diagnosis Text"),
        gr.Textbox(label="Prescribed Antibiotic (e.g., amoxicillin, none)")
    ],
    outputs=gr.Textbox(label="Prediction Result"),
    title="🧠 AI Antibiotic Misuse Detector (AAMD)",
    description="Enter patient and prescription details to check if the antibiotic use is appropriate.",
    theme="soft"
)

# ----------------------------
# STEP 7: Launch the app
# ----------------------------
app.launch()

import gradio as gr
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os
import matplotlib.pyplot as plt

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

# ----------------------------
# STEP 2: Rule-based misuse flag
# ----------------------------
def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

# ----------------------------
# STEP 3: Train AI model
# ----------------------------
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 4: Prediction function
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    # Rule-based detection
    if "viral" in diagnosis_text.lower() and meds != "none":
        result = "⚠️ Misuse: Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds == "none":
        result = "⚠️ Misuse: Missing antibiotic for bacterial infection"
    elif dose > 40:
        result = "⚠️ Misuse: Overdose detected"
    else:
        # AI prediction
        data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                            columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
        pred = model.predict(data)[0]
        result = "⚠️ Misuse detected" if pred == 1 else "✅ Appropriate Use"

    # ----------------------------
    # STEP 5: Log to CSV
    # ----------------------------
    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])

    log_file = "aamd_logs.csv"
    if os.path.exists(log_file):
        log_entry.to_csv(log_file, mode="a", header=False, index=False)
    else:
        log_entry.to_csv(log_file, index=False)

    return result


# ----------------------------
# STEP 6: Dashboard function
# ----------------------------
def dashboard():
    log_file = "aamd_logs.csv"
    if not os.path.exists(log_file):
        return "No data available yet. Run some predictions first.", None

    df_logs = pd.read_csv(log_file)

    total = len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse / total) * 100, 2)

    # Generate a simple chart
    misuse_reasons = df_logs["prediction"].value_counts()
    plt.figure(figsize=(6, 4))
    misuse_reasons.plot(kind="bar")
    plt.title("Common Antibiotic Misuse Reasons")
    plt.ylabel("Count")
    plt.tight_layout()
    chart_path = "misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()

    summary = f"""
    🧾 **AAMD Dashboard Summary**
    - Total predictions: {total}
    - Misuse cases: {misuse}
    - Misuse rate: {misuse_rate}%
    """

    return summary, chart_path


# ----------------------------
# STEP 7: Build Gradio tabs
# ----------------------------
with gr.Blocks(title="AI Antibiotic Misuse Detector") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (AAMD)")

    with gr.Tab("🔍 Prediction"):
        gr.Markdown("### Enter patient & prescription details to check misuse risk")
        age = gr.Number(label="Patient Age")
        dose = gr.Number(label="Antibiotic Dose (mg/kg)")
        prior_antibiotic = gr.Radio([0, 1], label="Prior Antibiotic Use (0=No, 1=Yes)")
        fever = gr.Radio([0, 1], label="Fever Present (0=No, 1=Yes)")
        diagnosis_text = gr.Textbox(label="Diagnosis Text")
        meds = gr.Textbox(label="Prescribed Antibiotic (e.g., amoxicillin, none)")
        output = gr.Textbox(label="Prediction Result")
        predict_button = gr.Button("Predict Misuse")
        predict_button.click(
            fn=predict_misuse,
            inputs=[age, dose, prior_antibiotic, fever, diagnosis_text, meds],
            outputs=output
        )

    with gr.Tab("📊 Dashboard"):
        gr.Markdown("### Antibiotic Misuse Analytics")
        refresh_button = gr.Button("🔄 Refresh Dashboard")
        summary = gr.Markdown()
        chart = gr.Image()
        refresh_button.click(fn=dashboard, inputs=None, outputs=[summary, chart])

# ----------------------------
# STEP 8: Launch app
# ----------------------------
app.launch()

import gradio as gr
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os
import matplotlib.pyplot as plt

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

# ----------------------------
# STEP 2: Rule-based misuse flag
# ----------------------------
def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

# ----------------------------
# STEP 3: Train AI model
# ----------------------------
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 4: Prediction function
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    if "viral" in diagnosis_text.lower() and meds != "none":
        result = "⚠️ Misuse: Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds == "none":
        result = "⚠️ Misuse: Missing antibiotic for bacterial infection"
    elif dose > 40:
        result = "⚠️ Misuse: Overdose detected"
    else:
        data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                            columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
        pred = model.predict(data)[0]
        result = "⚠️ Misuse detected" if pred == 1 else "✅ Appropriate Use"

    # Log result
    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])
    log_file = "aamd_logs.csv"
    if os.path.exists(log_file):
        log_entry.to_csv(log_file, mode="a", header=False, index=False)
    else:
        log_entry.to_csv(log_file, index=False)

    return result


# ----------------------------
# STEP 5: Recommendation System
# ----------------------------
def recommend_antibiotic(diagnosis_text, dose):
    diagnosis = diagnosis_text.lower()

    if "viral" in diagnosis:
        return "🦠 Likely viral infection — ❌ No antibiotic needed.\n💡 Recommend rest, hydration, and monitoring."

    if "pneumonia" in diagnosis:
        return "🧫 Bacterial infection — ✅ Recommend Amoxicillin or Azithromycin.\n💡 Typical dose: 10–30 mg/kg."

    if "urinary" in diagnosis or "cystitis" in diagnosis:
        return "💊 Possible UTI — ✅ Recommend Nitrofurantoin or Amoxicillin.\n💡 Ensure 5–7 day treatment."

    if dose > 40:
        return "⚠️ Overdose risk — adjust dose to 10–30 mg/kg based on body weight."

    return "✅ Current prescription appears within safe and effective range."

# ----------------------------
# STEP 6: Dashboard function
# ----------------------------
def dashboard():
    log_file = "aamd_logs.csv"
    if not os.path.exists(log_file):
        return "No data available yet. Run some predictions first.", None

    df_logs = pd.read_csv(log_file)
    total = len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse / total) * 100, 2)

    misuse_reasons = df_logs["prediction"].value_counts()
    plt.figure(figsize=(6, 4))
    misuse_reasons.plot(kind="bar")
    plt.title("Common Antibiotic Misuse Reasons")
    plt.ylabel("Count")
    plt.tight_layout()
    chart_path = "misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()

    summary = f"""
    🧾 **AAMD Dashboard Summary**
    - Total predictions: {total}
    - Misuse cases: {misuse}
    - Misuse rate: {misuse_rate}%
    """

    return summary, chart_path

# ----------------------------
# STEP 7: Build Gradio tabs
# ----------------------------
with gr.Blocks(title="AI Antibiotic Misuse Detector") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (AAMD)")

    with gr.Tab("🔍 Prediction"):
        gr.Markdown("### Enter patient & prescription details")
        age = gr.Number(label="Patient Age")
        dose = gr.Number(label="Antibiotic Dose (mg/kg)")
        prior_antibiotic = gr.Radio([0, 1], label="Prior Antibiotic Use (0=No, 1=Yes)")
        fever = gr.Radio([0, 1], label="Fever Present (0=No, 1=Yes)")
        diagnosis_text = gr.Textbox(label="Diagnosis Text")
        meds = gr.Textbox(label="Prescribed Antibiotic (e.g., amoxicillin, none)")
        output = gr.Textbox(label="Prediction Result")
        predict_button = gr.Button("Predict Misuse")
        predict_button.click(fn=predict_misuse,
                             inputs=[age, dose, prior_antibiotic, fever, diagnosis_text, meds],
                             outputs=output)

    with gr.Tab("💊 Recommendation"):
        gr.Markdown("### Get safer antibiotic recommendations based on diagnosis")
        diagnosis_input = gr.Textbox(label="Diagnosis Text")
        dose_input = gr.Number(label="Antibiotic Dose (mg/kg)")
        rec_output = gr.Textbox(label="Recommendation")
        rec_button = gr.Button("Get Recommendation")
        rec_button.click(fn=recommend_antibiotic,
                         inputs=[diagnosis_input, dose_input],
                         outputs=rec_output)

    with gr.Tab("📊 Dashboard"):
        gr.Markdown("### Antibiotic Misuse Analytics")
        refresh_button = gr.Button("🔄 Refresh Dashboard")
        summary = gr.Markdown()
        chart = gr.Image()
        refresh_button.click(fn=dashboard, inputs=None, outputs=[summary, chart])

# ----------------------------
# STEP 8: Launch app
# ----------------------------
app.launch()

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

# ----------------------------
# STEP 2: Misuse detection rules
# ----------------------------
def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

# ----------------------------
# STEP 3: Train Model
# ----------------------------
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 4: Prediction + Recommendation
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    # Rule-based check
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds == "none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose > 40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                            columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred == 1 else "Appropriate use"

    # Recommendation logic
    recommendation = ""
    if "viral" in diagnosis_text.lower():
        recommendation = "Avoid antibiotics — consider rest, fluids, and paracetamol."
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = "Use amoxicillin or azithromycin under prescription."
    elif dose > 40:
        recommendation = "Reduce antibiotic dose to recommended range (10–20 mg/kg)."
    else:
        recommendation = "Antibiotic usage seems appropriate."

    # Final message
    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n" \
             f"**Recommendation:** {recommendation}"

    # Log prediction
    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])

    log_file = "aamd_logs.csv"
    if os.path.exists(log_file):
        log_entry.to_csv(log_file, mode="a", header=False, index=False)
    else:
        log_entry.to_csv(log_file, index=False)

    return result


# ----------------------------
# STEP 5: Dashboard
# ----------------------------
def dashboard():
    log_file = "aamd_logs.csv"
    if not os.path.exists(log_file):
        return "No data yet. Run some predictions first.", None, None

    df_logs = pd.read_csv(log_file)
    total = len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse / total) * 100, 2)

    # Chart
    misuse_reasons = df_logs["prediction"].value_counts()
    plt.figure(figsize=(6, 4))
    misuse_reasons.plot(kind="bar", color="orange")
    plt.title("Common Misuse Reasons")
    plt.ylabel("Count")
    plt.tight_layout()
    chart_path = "misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()

    # Summary
    summary = f"""
    ### 🧾 Dashboard Summary
    - Total predictions: {total}
    - Misuse cases: {misuse}
    - Misuse rate: {misuse_rate}%
    """

    return summary, chart_path, df_logs


# ----------------------------
# STEP 6: Build Gradio UI
# ----------------------------
with gr.Blocks(title="AI Antibiotic Misuse Detector") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (AAMD)")
    gr.Markdown("### Smart AI System to Prevent Antibiotic Misuse and Recommend Safe Usage")

    with gr.Tab("🔍 Prediction"):
        gr.Markdown("Enter patient and prescription details below 👇")
        with gr.Row():
            age = gr.Number(label="Patient Age (years)")
            dose = gr.Number(label="Dose (mg/kg)")
        with gr.Row():
            prior_antibiotic = gr.Radio([0, 1], label="Prior Antibiotic Use (0=No, 1=Yes)")
            fever = gr.Radio([0, 1], label="Fever Present (0=No, 1=Yes)")
        diagnosis_text = gr.Textbox(label="Diagnosis Text (e.g. viral fever, pneumonia)")
        meds = gr.Textbox(label="Prescribed Antibiotic (e.g. amoxicillin, none)")
        output = gr.Markdown()
        btn = gr.Button("🧾 Predict Misuse & Recommend")
        btn.click(predict_misuse, [age, dose, prior_antibiotic, fever, diagnosis_text, meds], output)

    with gr.Tab("📊 Dashboard"):
        gr.Markdown("### Real-Time Analytics Dashboard")
        refresh = gr.Button("🔄 Refresh Dashboard")
        summary = gr.Markdown()
        chart = gr.Image()
        table = gr.Dataframe()
        refresh.click(dashboard, None, [summary, chart, table])

    with gr.Tab("📥 Download Logs"):
        gr.Markdown("### Download All Misuse Records as CSV")
        def download_logs():
            if os.path.exists("aamd_logs.csv"):
                return "aamd_logs.csv"
            return None
        download_button = gr.File(label="Download CSV Log", interactive=False)
        get_logs = gr.Button("📤 Generate Download Link")
        get_logs.click(download_logs, None, download_button)

app.launch()

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

# ----------------------------
# STEP 2: Misuse detection function
# ----------------------------
def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

# ----------------------------
# STEP 3: Train AI Model
# ----------------------------
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 4: Authentication System
# ----------------------------
USERS = {
    "doctor1": "doc123",
    "pharma1": "pharma123",
    "admin": "admin123"
}

SESSION = {"authenticated": False, "username": None}


def login(username, password):
    if username in USERS and USERS[username] == password:
        SESSION["authenticated"] = True
        SESSION["username"] = username
        return gr.update(visible=False), gr.update(visible=True), f"✅ Welcome, {username}!"
    else:
        return gr.update(), gr.update(visible=False), "❌ Invalid credentials. Try again."


def logout():
    SESSION["authenticated"] = False
    SESSION["username"] = None
    return gr.update(visible=True), gr.update(visible=False), "👋 You have been logged out."


# ----------------------------
# STEP 5: Misuse Prediction + Recommendation
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds == "none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose > 40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                            columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred == 1 else "Appropriate use"

    if "viral" in diagnosis_text.lower():
        recommendation = "Avoid antibiotics — consider rest, fluids, and paracetamol."
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = "Use amoxicillin or azithromycin under prescription."
    elif dose > 40:
        recommendation = "Reduce antibiotic dose to 10–20 mg/kg range."
    else:
        recommendation = "Antibiotic usage seems appropriate."

    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n" \
             f"**Recommendation:** {recommendation}"

    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": SESSION["username"],
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])

    log_file = "aamd_logs.csv"
    if os.path.exists(log_file):
        log_entry.to_csv(log_file, mode="a", header=False, index=False)
    else:
        log_entry.to_csv(log_file, index=False)

    return result


# ----------------------------
# STEP 6: Dashboard + Data Logs
# ----------------------------
def dashboard():
    log_file = "aamd_logs.csv"
    if not os.path.exists(log_file):
        return "No data yet. Run some predictions first.", None, None

    df_logs = pd.read_csv(log_file)
    total = len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse / total) * 100, 2)

    misuse_reasons = df_logs["prediction"].value_counts()
    plt.figure(figsize=(6, 4))
    misuse_reasons.plot(kind="bar", color="orange")
    plt.title("Common Misuse Reasons")
    plt.ylabel("Count")
    plt.tight_layout()
    chart_path = "misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()

    summary = f"""
    ### 🧾 Dashboard Summary
    - Total predictions: {total}
    - Misuse cases: {misuse}
    - Misuse rate: {misuse_rate}%
    """

    return summary, chart_path, df_logs


def download_logs():
    if os.path.exists("aamd_logs.csv"):
        return "aamd_logs.csv"
    return None


# ----------------------------
# STEP 7: Build Gradio Interface
# ----------------------------
with gr.Blocks(title="AI Antibiotic Misuse Detector (AAMD)") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (AAMD)")
    gr.Markdown("#### Secure System for Doctors & Pharmacists to Monitor Antibiotic Misuse")

    # Login section
    with gr.Group(visible=True) as login_section:
        gr.Markdown("### 🔐 Login")
        username = gr.Textbox(label="Username")
        password = gr.Textbox(label="Password", type="password")
        login_button = gr.Button("Login")
        login_message = gr.Markdown()

    # Main app section
    with gr.Group(visible=False) as main_app:
        gr.Markdown("## Welcome to the AAMD System")
        logout_button = gr.Button("🚪 Logout")

        with gr.Tab("🔍 Prediction"):
            gr.Markdown("### Enter patient & prescription details")
            age = gr.Number(label="Age (years)")
            dose = gr.Number(label="Antibiotic Dose (mg/kg)")
            prior_antibiotic = gr.Radio([0, 1], label="Prior Antibiotic Use (0=No, 1=Yes)")
            fever = gr.Radio([0, 1], label="Fever Present (0=No, 1=Yes)")
            diagnosis_text = gr.Textbox(label="Diagnosis (e.g., viral fever, pneumonia)")
            meds = gr.Textbox(label="Prescribed Antibiotic (e.g., amoxicillin, none)")
            output = gr.Markdown()
            predict_button = gr.Button("🧠 Predict Misuse & Recommend")
            predict_button.click(predict_misuse,
                                 [age, dose, prior_antibiotic, fever, diagnosis_text, meds],
                                 output)

        with gr.Tab("📊 Dashboard"):
            refresh_button = gr.Button("🔄 Refresh Dashboard")
            summary = gr.Markdown()
            chart = gr.Image()
            table = gr.Dataframe()
            refresh_button.click(dashboard, None, [summary, chart, table])

        with gr.Tab("📥 Download Logs"):
            gr.Markdown("### Download CSV Log File")
            download_button = gr.File(label="Download File", interactive=False)
            generate_link = gr.Button("📤 Generate Download Link")
            generate_link.click(download_logs, None, download_button)

    # Button logic
    login_button.click(login, [username, password], [login_section, main_app, login_message])
    logout_button.click(logout, None, [login_section, main_app, login_message])

app.launch()

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os

# ----------------------------
# STEP 1: Load antibiotic data
# ----------------------------
df = pd.read_csv("prescriptions.csv")

def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)
X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 2: User management system
# ----------------------------
USERS_FILE = "users.csv"
SESSION = {"authenticated": False, "username": None, "role": None}

# Initialize users.csv
if not os.path.exists(USERS_FILE):
    pd.DataFrame(columns=["username", "email", "password", "role"]).to_csv(USERS_FILE, index=False)


def signup(username, email, password, role):
    users = pd.read_csv(USERS_FILE)
    if username in users["username"].values:
        return "❌ Username already exists."
    new_user = pd.DataFrame([[username, email, password, role]], columns=["username", "email", "password", "role"])
    users = pd.concat([users, new_user], ignore_index=True)
    users.to_csv(USERS_FILE, index=False)
    return f"✅ Account created for {username} ({role}). You can now log in."


def login(username, password):
    users = pd.read_csv(USERS_FILE)
    match = users[(users["username"] == username) & (users["password"] == password)]
    if not match.empty:
        role = match.iloc[0]["role"]
        SESSION.update({"authenticated": True, "username": username, "role": role})
        return gr.update(visible=False), gr.update(visible=True), f"✅ Welcome {username}! Logged in as {role}."
    else:
        return gr.update(), gr.update(visible=False), "❌ Invalid credentials. Try again."


def logout():
    SESSION.update({"authenticated": False, "username": None, "role": None})
    return gr.update(visible=True), gr.update(visible=False), "👋 Logged out successfully."


# ----------------------------
# STEP 3: Prediction + Recommendation
# ----------------------------
def predict_misuse(age, dose, prior_antibiotic, fever, diagnosis_text, meds):
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds == "none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose > 40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age, dose, prior_antibiotic, fever]],
                            columns=["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred == 1 else "Appropriate use"

    if "viral" in diagnosis_text.lower():
        recommendation = "Avoid antibiotics — consider rest, fluids, and paracetamol."
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = "Use amoxicillin or azithromycin under prescription."
    elif dose > 40:
        recommendation = "Reduce antibiotic dose to 10–20 mg/kg."
    else:
        recommendation = "Antibiotic usage seems appropriate."

    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n" \
             f"**Recommendation:** {recommendation}"

    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": SESSION["username"],
        "role": SESSION["role"],
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])

    log_file = "aamd_logs.csv"
    if os.path.exists(log_file):
        log_entry.to_csv(log_file, mode="a", header=False, index=False)
    else:
        log_entry.to_csv(log_file, index=False)

    return result


# ----------------------------
# STEP 4: Dashboard
# ----------------------------
def dashboard():
    if not os.path.exists("aamd_logs.csv"):
        return "No data available.", None, None
    df_logs = pd.read_csv("aamd_logs.csv")
    total = len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse / total) * 100, 2)
    misuse_reasons = df_logs["prediction"].value_counts()
    plt.figure(figsize=(6, 4))
    misuse_reasons.plot(kind="bar", color="orange")
    plt.title("Antibiotic Misuse Patterns")
    plt.ylabel("Count")
    plt.tight_layout()
    chart_path = "misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()
    summary = f"### 🧾 Dashboard Summary\n- Total predictions: {total}\n- Misuse cases: {misuse}\n- Misuse rate: {misuse_rate}%"
    return summary, chart_path, df_logs


def download_logs():
    if os.path.exists("aamd_logs.csv"):
        return "aamd_logs.csv"
    return None


# ----------------------------
# STEP 5: Build Gradio UI
# ----------------------------
with gr.Blocks(title="AI Antibiotic Misuse Detector (AAMD)") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (AAMD)")
    gr.Markdown("#### Secure AI system for Doctors, Pharmacists & Admins")

    # Login/Signup page
    with gr.Group(visible=True) as auth_page:
        gr.Markdown("### 🔐 Login or Create Account")
        with gr.Tab("Login"):
            login_user = gr.Textbox(label="Username")
            login_pass = gr.Textbox(label="Password", type="password")
            login_btn = gr.Button("Login")
            login_msg = gr.Markdown()
        with gr.Tab("Signup"):
            signup_user = gr.Textbox(label="Username")
            signup_email = gr.Textbox(label="Email")
            signup_pass = gr.Textbox(label="Password", type="password")
            signup_role = gr.Dropdown(["Doctor", "Pharmacist", "Admin"], label="Role")
            signup_btn = gr.Button("Sign Up")
            signup_msg = gr.Markdown()

    # Main App
    with gr.Group(visible=False) as main_app:
        gr.Markdown("### Welcome to AAMD System")
        logout_btn = gr.Button("🚪 Logout")

        with gr.Tab("🔍 Prediction") as doctor_tab:
            gr.Markdown("### Misuse Prediction (Doctors Only)")
            age = gr.Number(label="Age (years)")
            dose = gr.Number(label="Dose (mg/kg)")
            prior_abx = gr.Radio([0, 1], label="Prior Antibiotic Use (0=No,1=Yes)")
            fever = gr.Radio([0, 1], label="Fever Present (0=No,1=Yes)")
            diagnosis = gr.Textbox(label="Diagnosis")
            meds = gr.Textbox(label="Prescribed Antibiotic")
            output = gr.Markdown()
            predict_btn = gr.Button("🧠 Predict & Recommend")
            predict_btn.click(predict_misuse, [age, dose, prior_abx, fever, diagnosis, meds], output)

        with gr.Tab("📊 Dashboard") as pharma_tab:
            gr.Markdown("### Analytics (Pharmacists & Admin)")
            refresh_btn = gr.Button("🔄 Refresh Dashboard")
            summary = gr.Markdown()
            chart = gr.Image()
            table = gr.Dataframe()
            refresh_btn.click(dashboard, None, [summary, chart, table])

        with gr.Tab("📥 Logs") as admin_tab:
            gr.Markdown("### Download Logs (Admin Only)")
            log_btn = gr.Button("📤 Generate Log File")
            log_file = gr.File(label="Download CSV", interactive=False)
            log_btn.click(download_logs, None, log_file)

    # Logic bindings
    login_btn.click(login, [login_user, login_pass], [auth_page, main_app, login_msg])
    logout_btn.click(logout, None, [auth_page, main_app, login_msg])
    signup_btn.click(signup, [signup_user, signup_email, signup_pass, signup_role], signup_msg)

app.launch()

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os
from fpdf import FPDF

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)

X = df[["age", "dose_mg_per_kg", "prior_abx_30d", "fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 2: User Management
# ----------------------------
USERS_FILE = "users.csv"
SESSION = {"authenticated": False, "username": None, "role": None}

if not os.path.exists(USERS_FILE):
    pd.DataFrame(columns=["username","email","password","role"]).to_csv(USERS_FILE,index=False)

def signup(username,email,password,role):
    users = pd.read_csv(USERS_FILE)
    if username in users["username"].values:
        return "❌ Username exists."
    new_user = pd.DataFrame([[username,email,password,role]],columns=["username","email","password","role"])
    users = pd.concat([users,new_user],ignore_index=True)
    users.to_csv(USERS_FILE,index=False)
    return f"✅ Account created for {username} ({role})"

def login(username,password):
    users = pd.read_csv(USERS_FILE)
    match = users[(users["username"]==username) & (users["password"]==password)]
    if not match.empty:
        role = match.iloc[0]["role"]
        SESSION.update({"authenticated": True,"username":username,"role":role})
        return gr.update(visible=False), gr.update(visible=True), f"✅ Welcome {username}! Role: {role}"
    else:
        return gr.update(), gr.update(visible=False), "❌ Invalid credentials"

def logout():
    SESSION.update({"authenticated": False,"username": None,"role": None})
    return gr.update(visible=True), gr.update(visible=False), "👋 Logged out"

# ----------------------------
# STEP 3: Prediction + Recommendation
# ----------------------------
def predict_misuse(age,dose,prior_antibiotic,fever,diagnosis_text,meds,lang="English"):
    misuse_type = ""
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds=="none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose>40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age,dose,prior_antibiotic,fever]],columns=["age","dose_mg_per_kg","prior_abx_30d","fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred==1 else "Appropriate use"

    # Multi-language recommendation
    rec_en = {"viral":"Avoid antibiotics; rest, fluids, paracetamol.",
              "pneumonia":"Use amoxicillin or azithromycin under prescription.",
              "overdose":"Reduce antibiotic dose to 10–20 mg/kg.",
              "ok":"Antibiotic usage seems appropriate."}
    rec_hi = {"viral":"एंटीबायोटिक्स से बचें; आराम करें, तरल पदार्थ लें, पैरासिटामॉल लें।",
              "pneumonia":"एमॉक्सिसिलिन या एजिथ्रोमाइसिन का प्रयोग करें।",
              "overdose":"खुराक 10–20 mg/kg तक कम करें।",
              "ok":"एंटीबायोटिक उपयोग उपयुक्त है।"}
    rec_dict = rec_en if lang=="English" else rec_hi

    if "viral" in diagnosis_text.lower():
        recommendation = rec_dict["viral"]
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = rec_dict["pneumonia"]
    elif dose>40:
        recommendation = rec_dict["overdose"]
    else:
        recommendation = rec_dict["ok"]

    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n**Recommendation:** {recommendation}"

    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": SESSION["username"],
        "role": SESSION["role"],
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])
    if os.path.exists("aamd_logs.csv"):
        log_entry.to_csv("aamd_logs.csv",mode="a",header=False,index=False)
    else:
        log_entry.to_csv("aamd_logs.csv",index=False)

    return result

# ----------------------------
# STEP 4: Dashboard + PDF Reports
# ----------------------------
def dashboard():
    if not os.path.exists("aamd_logs.csv"):
        return "No data yet.", None, None
    df_logs = pd.read_csv("aamd_logs.csv")
    total=len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate=round((misuse/total)*100,2)
    misuse_reasons=df_logs["prediction"].value_counts()
    plt.figure(figsize=(6,4))
    misuse_reasons.plot(kind="pie",autopct="%1.1f%%")
    plt.title("Misuse vs Proper Use")
    plt.tight_layout()
    chart_path="misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()
    summary=f"### Dashboard Summary\n- Total: {total}\n- Misuse: {misuse}\n- Misuse Rate: {misuse_rate}%"
    return summary, chart_path, df_logs

def generate_pdf(name,age,dose,diagnosis,meds,result):
    pdf=FPDF()
    pdf.add_page()
    pdf.set_font("Arial","B",16)
    pdf.cell(0,10,"Patient Report",ln=True,align="C")
    pdf.set_font("Arial","",12)
    pdf.ln(5)
    pdf.cell(0,10,f"Name: {name}",ln=True)
    pdf.cell(0,10,f"Age: {age}",ln=True)
    pdf.cell(0,10,f"Dose: {dose} mg/kg",ln=True)
    pdf.cell(0,10,f"Diagnosis: {diagnosis}",ln=True)
    pdf.cell(0,10,f"Prescribed meds: {meds}",ln=True)
    pdf.multi_cell(0,10,f"AI Analysis & Recommendation:\n{result}")
    filename=f"{name.replace(' ','_')}_report.pdf"
    pdf.output(filename)
    return filename

def download_logs():
    if os.path.exists("aamd_logs.csv"):
        return "aamd_logs.csv"
    return None

# ----------------------------
# STEP 5: Build Gradio Interface
# ----------------------------
with gr.Blocks(title="AAMD Advanced") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (AAMD Advanced)")
    gr.Markdown("#### Secure & Intelligent System with Multi-Language, Dashboard & PDF Reports")

    with gr.Group(visible=True) as auth_page:
        with gr.Tab("Login"):
            login_user=gr.Textbox(label="Username")
            login_pass=gr.Textbox(label="Password",type="password")
            login_btn=gr.Button("Login")
            login_msg=gr.Markdown()
        with gr.Tab("Signup"):
            signup_user=gr.Textbox(label="Username")
            signup_email=gr.Textbox(label="Email")
            signup_pass=gr.Textbox(label="Password",type="password")
            signup_role=gr.Dropdown(["Doctor","Pharmacist","Admin"],label="Role")
            signup_btn=gr.Button("Sign Up")
            signup_msg=gr.Markdown()

    with gr.Group(visible=False) as main_app:
        gr.Markdown("### Welcome to AAMD Advanced")
        logout_btn=gr.Button("🚪 Logout")

        with gr.Tab("🔍 Prediction") as doctor_tab:
            age=gr.Number(label="Age")
            dose=gr.Number(label="Dose (mg/kg)")
            prior_abx=gr.Radio([0,1],label="Prior Antibiotic Use")
            fever=gr.Radio([0,1],label="Fever Present")
            diagnosis=gr.Textbox(label="Diagnosis")
            meds=gr.Textbox(label="Prescribed Antibiotic")
            lang=gr.Dropdown(["English","Hindi"],label="Language")
            output=gr.Markdown()
            pdf_btn=gr.Button("Generate PDF Report")
            predict_btn=gr.Button("Predict & Recommend")
            predict_btn.click(predict_misuse,[age,dose,prior_abx,fever,diagnosis,meds,lang],output)
            pdf_btn.click(generate_pdf,[diagnosis,age,dose,diagnosis,meds,output],output)

        with gr.Tab("📊 Dashboard") as pharma_tab:
            refresh_btn=gr.Button("Refresh Dashboard")
            summary=gr.Markdown()
            chart=gr.Image()
            table=gr.Dataframe()
            refresh_btn.click(dashboard,None,[summary,chart,table])

        with gr.Tab("📥 Logs") as admin_tab:
            download_btn=gr.Button("Download Logs")
            download_file=gr.File(label="Download CSV",interactive=False)
            download_btn.click(download_logs,None,download_file)

    login_btn.click(login,[login_user,login_pass],[auth_page,main_app,login_msg])
    logout_btn.click(logout,None,[auth_page,main_app,login_msg])
    signup_btn.click(signup,[signup_user,signup_email,signup_pass,signup_role],signup_msg)

app.launch()



import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os
from fpdf import FPDF

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)
X = df[["age","dose_mg_per_kg","prior_abx_30d","fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 2: User Management
# ----------------------------
USERS_FILE = "users.csv"
SESSION = {"authenticated": False, "username": None, "role": None}

if not os.path.exists(USERS_FILE):
    pd.DataFrame(columns=["username","email","password","role"]).to_csv(USERS_FILE,index=False)

def signup(username,email,password,role):
    users = pd.read_csv(USERS_FILE)
    if username in users["username"].values:
        return "❌ Username exists."
    new_user = pd.DataFrame([[username,email,password,role]],columns=["username","email","password","role"])
    users = pd.concat([users,new_user],ignore_index=True)
    users.to_csv(USERS_FILE,index=False)
    return f"✅ Account created for {username} ({role})"

def login(username,password):
    users = pd.read_csv(USERS_FILE)
    match = users[(users["username"]==username) & (users["password"]==password)]
    if not match.empty:
        role = match.iloc[0]["role"]
        SESSION.update({"authenticated": True,"username":username,"role":role})
        return gr.update(visible=False), gr.update(visible=True), f"✅ Welcome {username}! Role: {role}"
    else:
        return gr.update(), gr.update(visible=False), "❌ Invalid credentials"

def logout():
    SESSION.update({"authenticated": False,"username": None,"role": None})
    return gr.update(visible=True), gr.update(visible=False), "👋 Logged out"

# ----------------------------
# STEP 3: Misuse Prediction + Recommendation
# ----------------------------
def predict_misuse(age,dose,prior_antibiotic,fever,diagnosis_text,meds,lang="English"):
    misuse_type = ""
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds=="none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose>40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age,dose,prior_antibiotic,fever]],columns=["age","dose_mg_per_kg","prior_abx_30d","fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred==1 else "Appropriate use"

    rec_en = {"viral":"Avoid antibiotics; rest, fluids, paracetamol.",
              "pneumonia":"Use amoxicillin or azithromycin under prescription.",
              "overdose":"Reduce antibiotic dose to 10–20 mg/kg.",
              "ok":"Antibiotic usage seems appropriate."}
    rec_hi = {"viral":"एंटीबायोटिक्स से बचें; आराम करें, तरल पदार्थ लें, पैरासिटामॉल लें।",
              "pneumonia":"एमॉक्सिसिलिन या एजिथ्रोमाइसिन का प्रयोग करें।",
              "overdose":"खुराक 10–20 mg/kg तक कम करें।",
              "ok":"एंटीबायोटिक उपयोग उपयुक्त है।"}
    rec_dict = rec_en if lang=="English" else rec_hi

    if "viral" in diagnosis_text.lower():
        recommendation = rec_dict["viral"]
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = rec_dict["pneumonia"]
    elif dose>40:
        recommendation = rec_dict["overdose"]
    else:
        recommendation = rec_dict["ok"]

    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n**Recommendation:** {recommendation}"

    # Smart alert
    if "misuse" in misuse_type.lower() or dose>40:
        result += "\n\n🚨 **ALERT:** Check prescription carefully!"

    # Save log
    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": SESSION["username"],
        "role": SESSION["role"],
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])
    if os.path.exists("aamd_logs.csv"):
        log_entry.to_csv("aamd_logs.csv",mode="a",header=False,index=False)
    else:
        log_entry.to_csv("aamd_logs.csv",index=False)

    return result

# ----------------------------
# STEP 4: Dashboard + Reports
# ----------------------------
def dashboard():
    if not os.path.exists("aamd_logs.csv"):
        return "No data yet.", None, None
    df_logs = pd.read_csv("aamd_logs.csv")
    total=len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse/total)*100,2)
    plt.figure(figsize=(6,4))
    df_logs["prediction"].str.contains("Misuse").value_counts().plot(kind="pie",autopct="%1.1f%%")
    plt.title("Misuse vs Proper Use")
    plt.tight_layout()
    chart_path="misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()
    summary=f"### Dashboard Summary\n- Total: {total}\n- Misuse: {misuse}\n- Misuse Rate: {misuse_rate}%"
    return summary, chart_path, df_logs

def generate_pdf(name,age,dose,diagnosis,meds,result):
    pdf=FPDF()
    pdf.add_page()
    pdf.set_font("Arial","B",16)
    pdf.cell(0,10,"Patient Report",ln=True,align="C")
    pdf.set_font("Arial","",12)
    pdf.ln(5)
    pdf.cell(0,10,f"Name: {name}",ln=True)
    pdf.cell(0,10,f"Age: {age}",ln=True)
    pdf.cell(0,10,f"Dose: {dose} mg/kg",ln=True)
    pdf.cell(0,10,f"Diagnosis: {diagnosis}",ln=True)
    pdf.cell(0,10,f"Prescribed meds: {meds}",ln=True)
    pdf.multi_cell(0,10,f"AI Analysis & Recommendation:\n{result}")
    filename=f"{name.replace(' ','_')}_report.pdf"
    pdf.output(filename)
    return filename

def download_logs():
    if os.path.exists("aamd_logs.csv"):
        return "aamd_logs.csv"
    return None

# ----------------------------
# STEP 5: Symptom-to-Diagnosis helper
# ----------------------------
def symptom_helper(symptoms):
    symptoms = symptoms.lower()
    if "fever" in symptoms and "cough" in symptoms:
        return "Likely Pneumonia (bacterial)"
    elif "sore throat" in symptoms:
        return "Likely Viral Infection"
    elif "diarrhea" in symptoms:
        return "Likely Bacterial Gastroenteritis"
    else:
        return "Consult doctor for proper diagnosis"

# ----------------------------
# STEP 6: Doctor Chatbot (simple rule-based)
# ----------------------------
def chatbot(message):
    msg = message.lower()
    if "antibiotic" in msg and "viral" in msg:
        return "Avoid antibiotics for viral infections. Recommend rest and fluids."
    elif "dose" in msg:
        return "Typical pediatric dose is 10–20 mg/kg. Adjust per doctor guidance."
    elif "side effect" in msg:
        return "Common side effects: nausea, diarrhea, rash. Severe reactions require medical attention."
    else:
        return "Please consult your hospital protocol or senior doctor."

# ----------------------------
# STEP 7: Build Gradio Interface
# ----------------------------
with gr.Blocks(title="AAMD Next-Gen") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (Next-Gen)")
    gr.Markdown("Secure, Multi-Language, Chatbot, Dashboard & Alerts")

    # Login/Signup
    with gr.Group(visible=True) as auth_page:
        with gr.Tab("Login"):
            login_user=gr.Textbox(label="Username")
            login_pass=gr.Textbox(label="Password",type="password")
            login_btn=gr.Button("Login")
            login_msg=gr.Markdown()
        with gr.Tab("Signup"):
            signup_user=gr.Textbox(label="Username")
            signup_email=gr.Textbox(label="Email")
            signup_pass=gr.Textbox(label="Password",type="password")
            signup_role=gr.Dropdown(["Doctor","Pharmacist","Admin"],label="Role")
            signup_btn=gr.Button("Sign Up")
            signup_msg=gr.Markdown()

    # Main App
    with gr.Group(visible=False) as main_app:
        gr.Markdown("### Welcome to AAMD Next-Gen System")
        logout_btn=gr.Button("🚪 Logout")

        with gr.Tab("🔍 Prediction") as doctor_tab:
            age=gr.Number(label="Age")
            dose=gr.Number(label="Dose (mg/kg)")
            prior_abx=gr.Radio([0,1],label="Prior Antibiotic Use")
            fever=gr.Radio([0,1],label="Fever Present")
            diagnosis=gr.Textbox(label="Diagnosis")
            meds=gr.Textbox(label="Prescribed Antibiotic")
            lang=gr.Dropdown(["English","Hindi"],label="Language")
            output=gr.Markdown()
            pdf_btn=gr.Button("Generate PDF Report")
            predict_btn=gr.Button("Predict & Recommend")
            predict_btn.click(predict_misuse,[age,dose,prior_abx,fever,diagnosis,meds,lang],output)
            pdf_btn.click(generate_pdf,[diagnosis,age,dose,diagnosis,meds,output],output)

        with gr.Tab("📊 Dashboard") as pharma_tab:
            refresh_btn=gr.Button("Refresh Dashboard")
            summary=gr.Markdown()
            chart=gr.Image()
            table=gr.Dataframe()
            refresh_btn.click(dashboard,None,[summary,chart,table])

        with gr.Tab("💬 Chatbot") as chat_tab:
            chatbot_input=gr.Textbox(label="Ask your question...")
            chatbot_output=gr.Markdown()
            chatbot_btn=gr.Button("Send")
            chatbot_btn.click(chatbot,[chatbot_input],chatbot_output)

        with gr.Tab("📥 Logs") as admin_tab:
            download_btn=gr.Button("Download Logs")
            download_file=gr.File(label="Download CSV",interactive=False)
            download_btn.click(download_logs,None,download_file)

    # Logic bindings
    login_btn.click(login,[login_user,login_pass],[auth_page,main_app,login_msg])
    logout_btn.click(logout,None,[auth_page,main_app,login_msg])
    signup_btn.click(signup,[signup_user,signup_email,signup_pass,signup_role],signup_msg)

app.launch()

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
import os
from fpdf import FPDF

# ----------------------------
# STEP 1: Load dataset
# ----------------------------
df = pd.read_csv("prescriptions.csv")

def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)
X = df[["age","dose_mg_per_kg","prior_abx_30d","fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# ----------------------------
# STEP 2: User Management
# ----------------------------
USERS_FILE = "users.csv"
SESSION = {"authenticated": False, "username": None, "role": None}

if not os.path.exists(USERS_FILE):
    pd.DataFrame(columns=["username","email","password","role"]).to_csv(USERS_FILE,index=False)

def signup(username,email,password,role):
    users = pd.read_csv(USERS_FILE)
    if username in users["username"].values:
        return "❌ Username exists."
    new_user = pd.DataFrame([[username,email,password,role]],columns=["username","email","password","role"])
    users = pd.concat([users,new_user],ignore_index=True)
    users.to_csv(USERS_FILE,index=False)
    return f"✅ Account created for {username} ({role})"

def login(username,password):
    users = pd.read_csv(USERS_FILE)
    match = users[(users["username"]==username) & (users["password"]==password)]
    if not match.empty:
        role = match.iloc[0]["role"]
        SESSION.update({"authenticated": True,"username":username,"role":role})
        return gr.update(visible=False), gr.update(visible=True), f"✅ Welcome {username}! Role: {role}"
    else:
        return gr.update(), gr.update(visible=False), "❌ Invalid credentials"

def logout():
    SESSION.update({"authenticated": False,"username": None,"role": None})
    return gr.update(visible=True), gr.update(visible=False), "👋 Logged out"

# ----------------------------
# STEP 3: Misuse Prediction + Recommendation
# ----------------------------
def predict_misuse(age,dose,prior_antibiotic,fever,diagnosis_text,meds,lang="English"):
    misuse_type = ""
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds=="none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose>40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age,dose,prior_antibiotic,fever]],columns=["age","dose_mg_per_kg","prior_abx_30d","fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred==1 else "Appropriate use"

    rec_en = {"viral":"Avoid antibiotics; rest, fluids, paracetamol.",
              "pneumonia":"Use amoxicillin or azithromycin under prescription.",
              "overdose":"Reduce antibiotic dose to 10–20 mg/kg.",
              "ok":"Antibiotic usage seems appropriate."}
    rec_hi = {"viral":"एंटीबायोटिक्स से बचें; आराम करें, तरल पदार्थ लें, पैरासिटामॉल लें।",
              "pneumonia":"एमॉक्सिसिलिन या एजिथ्रोमाइसिन का प्रयोग करें।",
              "overdose":"खुराक 10–20 mg/kg तक कम करें।",
              "ok":"एंटीबायोटिक उपयोग उपयुक्त है।"}
    rec_dict = rec_en if lang=="English" else rec_hi

    if "viral" in diagnosis_text.lower():
        recommendation = rec_dict["viral"]
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = rec_dict["pneumonia"]
    elif dose>40:
        recommendation = rec_dict["overdose"]
    else:
        recommendation = rec_dict["ok"]

    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n**Recommendation:** {recommendation}"

    # Smart alert
    if "misuse" in misuse_type.lower() or dose>40:
        result += "\n\n🚨 **ALERT:** Check prescription carefully!"

    # Save log
    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": SESSION["username"],
        "role": SESSION["role"],
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_antibiotic,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])
    if os.path.exists("aamd_logs.csv"):
        log_entry.to_csv("aamd_logs.csv",mode="a",header=False,index=False)
    else:
        log_entry.to_csv("aamd_logs.csv",index=False)

    return result

# ----------------------------
# STEP 4: Dashboard + Reports
# ----------------------------
def dashboard():
    if not os.path.exists("aamd_logs.csv"):
        return "No data yet.", None, None
    df_logs = pd.read_csv("aamd_logs.csv")
    total=len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse/total)*100,2)
    plt.figure(figsize=(6,4))
    df_logs["prediction"].str.contains("Misuse").value_counts().plot(kind="pie",autopct="%1.1f%%")
    plt.title("Misuse vs Proper Use")
    plt.tight_layout()
    chart_path="misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()
    summary=f"### Dashboard Summary\n- Total: {total}\n- Misuse: {misuse}\n- Misuse Rate: {misuse_rate}%"
    return summary, chart_path, df_logs

def generate_pdf(name,age,dose,diagnosis,meds,result):
    pdf=FPDF()
    pdf.add_page()
    pdf.set_font("Arial","B",16)
    pdf.cell(0,10,"Patient Report",ln=True,align="C")
    pdf.set_font("Arial","",12)
    pdf.ln(5)
    pdf.cell(0,10,f"Name: {name}",ln=True)
    pdf.cell(0,10,f"Age: {age}",ln=True)
    pdf.cell(0,10,f"Dose: {dose} mg/kg",ln=True)
    pdf.cell(0,10,f"Diagnosis: {diagnosis}",ln=True)
    pdf.cell(0,10,f"Prescribed meds: {meds}",ln=True)
    pdf.multi_cell(0,10,f"AI Analysis & Recommendation:\n{result}")
    filename=f"{name.replace(' ','_')}_report.pdf"
    pdf.output(filename)
    return filename

def download_logs():
    if os.path.exists("aamd_logs.csv"):
        return "aamd_logs.csv"
    return None

# ----------------------------
# STEP 5: Symptom-to-Diagnosis helper
# ----------------------------
def symptom_helper(symptoms):
    symptoms = symptoms.lower()
    if "fever" in symptoms and "cough" in symptoms:
        return "Likely Pneumonia (bacterial)"
    elif "sore throat" in symptoms:
        return "Likely Viral Infection"
    elif "diarrhea" in symptoms:
        return "Likely Bacterial Gastroenteritis"
    else:
        return "Consult doctor for proper diagnosis"

# ----------------------------
# STEP 6: Doctor Chatbot (simple rule-based)
# ----------------------------
def chatbot(message):
    msg = message.lower()
    if "antibiotic" in msg and "viral" in msg:
        return "Avoid antibiotics for viral infections. Recommend rest and fluids."
    elif "dose" in msg:
        return "Typical pediatric dose is 10–20 mg/kg. Adjust per doctor guidance."
    elif "side effect" in msg:
        return "Common side effects: nausea, diarrhea, rash. Severe reactions require medical attention."
    else:
        return "Please consult your hospital protocol or senior doctor."

# ----------------------------
# STEP 7: Build Gradio Interface
# ----------------------------
with gr.Blocks(title="AAMD Next-Gen") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (Next-Gen)")
    gr.Markdown("Secure, Multi-Language, Chatbot, Dashboard & Alerts")

    # Login/Signup
    with gr.Group(visible=True) as auth_page:
        with gr.Tab("Login"):
            login_user=gr.Textbox(label="Username")
            login_pass=gr.Textbox(label="Password",type="password")
            login_btn=gr.Button("Login")
            login_msg=gr.Markdown()
        with gr.Tab("Signup"):
            signup_user=gr.Textbox(label="Username")
            signup_email=gr.Textbox(label="Email")
            signup_pass=gr.Textbox(label="Password",type="password")
            signup_role=gr.Dropdown(["Doctor","Pharmacist","Admin"],label="Role")
            signup_btn=gr.Button("Sign Up")
            signup_msg=gr.Markdown()

    # Main App
    with gr.Group(visible=False) as main_app:
        gr.Markdown("### Welcome to AAMD Next-Gen System")
        logout_btn=gr.Button("🚪 Logout")

        with gr.Tab("🔍 Prediction") as doctor_tab:
            age=gr.Number(label="Age")
            dose=gr.Number(label="Dose (mg/kg)")
            prior_abx=gr.Radio([0,1],label="Prior Antibiotic Use")
            fever=gr.Radio([0,1],label="Fever Present")
            diagnosis=gr.Textbox(label="Diagnosis")
            meds=gr.Textbox(label="Prescribed Antibiotic")
            lang=gr.Dropdown(["English","Hindi"],label="Language")
            output=gr.Markdown()
            pdf_btn=gr.Button("Generate PDF Report")
            predict_btn=gr.Button("Predict & Recommend")
            predict_btn.click(predict_misuse,[age,dose,prior_abx,fever,diagnosis,meds,lang],output)
            pdf_btn.click(generate_pdf,[diagnosis,age,dose,diagnosis,meds,output],output)

        with gr.Tab("📊 Dashboard") as pharma_tab:
            refresh_btn=gr.Button("Refresh Dashboard")
            summary=gr.Markdown()
            chart=gr.Image()
            table=gr.Dataframe()
            refresh_btn.click(dashboard,None,[summary,chart,table])

        with gr.Tab("💬 Chatbot") as chat_tab:
            chatbot_input=gr.Textbox(label="Ask your question...")
            chatbot_output=gr.Markdown()
            chatbot_btn=gr.Button("Send")
            chatbot_btn.click(chatbot,[chatbot_input],chatbot_output)

        with gr.Tab("📥 Logs") as admin_tab:
            download_btn=gr.Button("Download Logs")
            download_file=gr.File(label="Download CSV",interactive=False)
            download_btn.click(download_logs,None,download_file)

    # Logic bindings
    login_btn.click(login,[login_user,login_pass],[auth_page,main_app,login_msg])
    logout_btn.click(logout,None,[auth_page,main_app,login_msg])
    signup_btn.click(signup,[signup_user,signup_email,signup_pass,signup_role],signup_msg)

app.launch()

import pandas as pd

# ----------------------------
# 1️⃣ Create prescriptions.csv
# ----------------------------
prescriptions_data = [
    [5,20,0,1,"viral infection","none"],
    [12,25,1,1,"pneumonia","amoxicillin"],
    [7,50,0,1,"viral infection","azithromycin"],
    [30,15,0,0,"bacterial gastroenteritis","none"],
    [8,18,1,1,"pneumonia","none"],
    [15,22,0,0,"viral infection","none"],
    [6,45,1,1,"viral infection","amoxicillin"],
    [10,20,0,0,"pneumonia","azithromycin"]
]

prescriptions_df = pd.DataFrame(prescriptions_data, columns=[
    "age","dose_mg_per_kg","prior_abx_30d","fever_flag","diagnosis_text","meds"
])

prescriptions_df.to_csv("prescriptions.csv", index=False)
print("✅ prescriptions.csv created successfully!")

# ----------------------------
# 2️⃣ Create users.csv
# ----------------------------
users_data = [
    ["doctor1","doctor1@example.com","doc123","Doctor"],
    ["pharma1","pharma1@example.com","pharmacist123","Pharmacist"],
    ["admin","admin@example.com","admin123","Admin"]
]

users_df = pd.DataFrame(users_data, columns=["username","email","password","role"])
users_df.to_csv("users.csv", index=False)
print("✅ users.csv created successfully!")

import os
import pandas as pd
import gradio as gr
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime
from fpdf import FPDF # Import FPDF here
import matplotlib.pyplot as plt

# ----------------------------
# 1️⃣ Generate CSV files if not exist
# ----------------------------
if not os.path.exists("prescriptions.csv"):
    prescriptions_data = [
        [5,20,0,1,"viral infection","none"],
        [12,25,1,1,"pneumonia","amoxicillin"],
        [7,50,0,1,"viral infection","azithromycin"],
        [30,15,0,0,"bacterial gastroenteritis","none"],
        [8,18,1,1,"pneumonia","none"],
        [15,22,0,0,"viral infection","none"],
        [6,45,1,1,"viral infection","amoxicillin"],
        [10,20,0,0,"pneumonia","azithromycin"]
    ]
    prescriptions_df = pd.DataFrame(prescriptions_data, columns=[
        "age","dose_mg_per_kg","prior_abx_30d","fever_flag","diagnosis_text","meds"
    ])
    prescriptions_df.to_csv("prescriptions.csv", index=False)
    print("✅ prescriptions.csv created!")

if not os.path.exists("users.csv"):
    users_data = [
        ["doctor1","doctor1@example.com","doc123","Doctor"],
        ["pharma1","pharma1@example.com","pharmacist123","Pharmacist"],
        ["admin","admin@example.com","admin123","Admin"]
    ]
    users_df = pd.DataFrame(users_data, columns=["username","email","password","role"])
    users_df.to_csv("users.csv", index=False)
    print("✅ users.csv created!")

# ----------------------------
# 2️⃣ Launch full AAMD Gradio app
# ----------------------------


# Load dataset
df = pd.read_csv("prescriptions.csv")

def detect_misuse(row):
    if "viral" in row["diagnosis_text"].lower() and row["meds"] != "none":
        return 1
    if "pneumonia" in row["diagnosis_text"].lower() and row["meds"] == "none":
        return 1
    if row["dose_mg_per_kg"] > 40:
        return 1
    return 0

df["misuse_flag"] = df.apply(detect_misuse, axis=1)
X = df[["age","dose_mg_per_kg","prior_abx_30d","fever_flag"]]
y = df["misuse_flag"]
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# Session and CSV paths
USERS_FILE = "users.csv"
SESSION = {"authenticated": False, "username": None, "role": None, "theme":"light","lang":"English"}

# ----------------------------
# User Management functions
# ----------------------------
def signup(username,email,password,role,lang="English"):
    users = pd.read_csv(USERS_FILE)
    if username in users["username"].values:
        return "❌ Username exists." if lang=="English" else "❌ उपयोगकर्ता पहले से मौजूद है।"
    new_user = pd.DataFrame([[username,email,password,role]],columns=["username","email","password","role"])
    users = pd.concat([users,new_user],ignore_index=True)
    users.to_csv(USERS_FILE,index=False)
    return f"✅ Account created for {username} ({role})" if lang=="English" else f"✅ खाता {username} ({role}) के लिए बनाया गया।"

def login(username,password,lang="English"):
    users = pd.read_csv(USERS_FILE)
    match = users[(users["username"]==username) & (users["password"]==password)]
    if not match.empty:
        role = match.iloc[0]["role"]
        SESSION.update({"authenticated": True,"username":username,"role":role})
        msg = f"✅ Welcome {username}! Role: {role}" if lang=="English" else f"✅ स्वागत {username}! भूमिका: {role}"
        return gr.update(visible=False), gr.update(visible=True), msg
    else:
        msg = "❌ Invalid credentials" if lang=="English" else "❌ अमान्य प्रमाण-पत्र"
        return gr.update(), gr.update(visible=False), msg

def logout(lang="English"):
    SESSION.update({"authenticated": False,"username": None,"role": None})
    msg = "👋 Logged out" if lang=="English" else "👋 लॉग आउट हुआ"
    return gr.update(visible=True), gr.update(visible=False), msg

# ----------------------------
# Misuse Prediction
# ----------------------------
def predict_misuse(age,dose,prior_abx,fever,diagnosis_text,meds,ui_lang="English"):
    misuse_type = ""
    if "viral" in diagnosis_text.lower() and meds != "none":
        misuse_type = "Antibiotic for viral infection"
    elif "pneumonia" in diagnosis_text.lower() and meds=="none":
        misuse_type = "Missing antibiotic for bacterial infection"
    elif dose>40:
        misuse_type = "Overdose detected"
    else:
        data = pd.DataFrame([[age,dose,prior_abx,fever]],columns=["age","dose_mg_per_kg","prior_abx_30d","fever_flag"])
        pred = model.predict(data)[0]
        misuse_type = "AI-detected misuse" if pred==1 else "Appropriate use"

    rec_en = {"viral":"Avoid antibiotics; rest, fluids, paracetamol.",
              "pneumonia":"Use amoxicillin or azithromycin under prescription.",
              "overdose":"Reduce antibiotic dose to 10–20 mg/kg.",
              "ok":"Antibiotic usage seems appropriate."}
    rec_hi = {"viral":"एंटीबायोटिक्स से बचें; आराम करें, तरल पदार्थ लें, पैरासिटामॉल लें।",
              "pneumonia":"एमॉक्सिसिलिन या एजिथ्रोमाइसिन का प्रयोग करें।",
              "overdose":"खुराक 10–20 mg/kg तक कम करें।",
              "ok":"एंटीबायोटिक उपयोग उपयुक्त है।"}
    rec_dict = rec_en if ui_lang=="English" else rec_hi

    if "viral" in diagnosis_text.lower():
        recommendation = rec_dict["viral"]
    elif "pneumonia" in diagnosis_text.lower():
        recommendation = rec_dict["pneumonia"]
    elif dose>40:
        recommendation = rec_dict["overdose"]
    else:
        recommendation = rec_dict["ok"]

    result = f"**Result:** {'⚠️ Misuse Detected' if 'misuse' in misuse_type.lower() else '✅ Appropriate Use'}\n\n" \
             f"**Reason:** {misuse_type}\n\n**Recommendation:** {recommendation}"

    if "misuse" in misuse_type.lower() or dose>40:
        alert_msg = "🚨 ALERT: Check prescription carefully!" if ui_lang=="English" else "🚨 चेतावनी: कृपया प्रिस्क्रिप्शन जांचें!"
        result += f"\n\n{alert_msg}"

    log_entry = pd.DataFrame([{
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": SESSION["username"],
        "role": SESSION["role"],
        "age": age,
        "dose_mg_per_kg": dose,
        "prior_abx_30d": prior_abx,
        "fever_flag": fever,
        "diagnosis_text": diagnosis_text,
        "meds": meds,
        "prediction": result
    }])
    if os.path.exists("aamd_logs.csv"):
        log_entry.to_csv("aamd_logs.csv",mode="a",header=False,index=False)
    else:
        log_entry.to_csv("aamd_logs.csv",index=False)

    return result

# ----------------------------
# Dashboard + Reports functions
# ----------------------------
def dashboard():
    if not os.path.exists("aamd_logs.csv"):
        return "No data yet.", None, None
    df_logs = pd.read_csv("aamd_logs.csv")
    total=len(df_logs)
    misuse = df_logs["prediction"].str.contains("Misuse").sum()
    misuse_rate = round((misuse/total)*100,2)
    plt.figure(figsize=(6,4))
    df_logs["prediction"].str.contains("Misuse").value_counts().plot(kind="pie",autopct="%1.1f%%")
    plt.title("Misuse vs Proper Use")
    plt.tight_layout()
    chart_path="misuse_chart.png"
    plt.savefig(chart_path)
    plt.close()
    summary=f"### Dashboard Summary\n- Total: {total}\n- Misuse: {misuse}\n- Misuse Rate: {misuse_rate}%"
    return summary, chart_path, df_logs

def generate_pdf(name,age,dose,diagnosis,meds,result):
    pdf=FPDF()
    pdf.add_page()
    pdf.set_font("Arial","B",16)
    pdf.cell(0,10,"Patient Report",ln=True,align="C")
    pdf.set_font("Arial","",12)
    pdf.ln(5)
    pdf.cell(0,10,f"Name: {name}",ln=True)
    pdf.cell(0,10,f"Age: {age}",ln=True)
    pdf.cell(0,10,f"Dose: {dose} mg/kg",ln=True)
    pdf.cell(0,10,f"Diagnosis: {diagnosis}",ln=True)
    pdf.cell(0,10,f"Prescribed meds: {meds}",ln=True)
    pdf.multi_cell(0,10,f"AI Analysis & Recommendation:\n{result}")
    filename=f"{name.replace(' ','_')}_report.pdf"
    pdf.output(filename)
    return filename

def download_logs():
    if os.path.exists("aamd_logs.csv"):
        return "aamd_logs.csv"
    return None

# ----------------------------
# Symptom-to-Diagnosis helper
# ----------------------------
def symptom_helper(symptoms):
    symptoms = symptoms.lower()
    if "fever" in symptoms and "cough" in symptoms:
        return "Likely Pneumonia (bacterial)"
    elif "sore throat" in symptoms:
        return "Likely Viral Infection"
    elif "diarrhea" in symptoms:
        return "Likely Bacterial Gastroenteritis"
    else:
        return "Consult doctor for proper diagnosis"

# ----------------------------
# Doctor Chatbot (simple rule-based)
# ----------------------------
def chatbot(message):
    msg = message.lower()
    if "antibiotic" in msg and "viral" in msg:
        return "Avoid antibiotics for viral infections. Recommend rest and fluids."
    elif "dose" in msg:
        return "Typical pediatric dose is 10–20 mg/kg. Adjust per doctor guidance."
    elif "side effect" in msg:
        return "Common side effects: nausea, diarrhea, rash. Severe reactions require medical attention."
    else:
        return "Please consult your hospital protocol or senior doctor."


# ----------------------------
# Build Gradio Interface
# ----------------------------
with gr.Blocks(title="AAMD Next-Gen") as app:
    gr.Markdown("# 🧠 AI Antibiotic Misuse Detector (Next-Gen)")
    gr.Markdown("Secure, Multi-Language, Chatbot, Dashboard & Alerts")

    # Login/Signup
    with gr.Group(visible=True) as auth_page:
        with gr.Tab("Login"):
            login_user=gr.Textbox(label="Username")
            login_pass=gr.Textbox(label="Password",type="password")
            login_btn=gr.Button("Login")
            login_msg=gr.Markdown()
        with gr.Tab("Signup"):
            signup_user=gr.Textbox(label="Username")
            signup_email=gr.Textbox(label="Email")
            signup_pass=gr.Textbox(label="Password",type="password")
            signup_role=gr.Dropdown(["Doctor","Pharmacist","Admin"],label="Role")
            signup_btn=gr.Button("Sign Up")
            signup_msg=gr.Markdown()

    # Main App
    with gr.Group(visible=False) as main_app:
        gr.Markdown("### Welcome to AAMD Next-Gen System")
        logout_btn=gr.Button("🚪 Logout")

        with gr.Tab("🔍 Prediction") as doctor_tab:
            age=gr.Number(label="Age")
            dose=gr.Number(label="Dose (mg/kg)")
            prior_abx=gr.Radio([0,1],label="Prior Antibiotic Use")
            fever=gr.Radio([0,1],label="Fever Present")
            diagnosis=gr.Textbox(label="Diagnosis")
            meds=gr.Textbox(label="Prescribed Antibiotic")
            lang=gr.Dropdown(["English","Hindi"],label="Language")
            output=gr.Markdown()
            pdf_btn=gr.Button("Generate PDF Report")
            predict_btn=gr.Button("Predict & Recommend")
            predict_btn.click(predict_misuse,[age,dose,prior_abx,fever,diagnosis,meds,lang],output)
            pdf_btn.click(generate_pdf,[diagnosis,age,dose,diagnosis,meds,output],output) # TODO: Pass patient name for PDF

        with gr.Tab("📊 Dashboard") as pharma_tab:
            refresh_btn=gr.Button("Refresh Dashboard")
            summary=gr.Markdown()
            chart=gr.Image()
            table=gr.Dataframe()
            refresh_btn.click(dashboard,None,[summary,chart,table])

        with gr.Tab("💬 Chatbot") as chat_tab:
            chatbot_input=gr.Textbox(label="Ask your question...")
            chatbot_output=gr.Markdown()
            chatbot_btn=gr.Button("Send")
            chatbot_btn.click(chatbot,[chatbot_input],chatbot_output)

        with gr.Tab("📥 Logs") as admin_tab:
            download_btn=gr.Button("Download Logs")
            download_file=gr.File(label="Download CSV",interactive=False)
            download_btn.click(download_logs,None,download_file)

    # Logic bindings
    login_btn.click(login,[login_user,login_pass],[auth_page,main_app,login_msg])
    logout_btn.click(logout,None,[auth_page,main_app,login_msg])
    signup_btn.click(signup,[signup_user,signup_email,signup_pass,signup_role],signup_msg)

import os

port = int(os.environ.get("PORT", 7860))

app.launch(
    server_name="0.0.0.0",
    server_port=port
)
print("✅ CSV files generated and AAMD app launched successfully!")

# ----------------------------
# 7️⃣ Chatbot function
# ----------------------------
def chatbot(message, ui_lang="English"):
    msg = message.lower()
    # Simple rule-based responses
    if "antibiotic" in msg and "viral" in msg:
        return ("Avoid antibiotics for viral infections. Rest and fluids recommended."
                if ui_lang=="English"
                else "वायरल संक्रमण के लिए एंटीबायोटिक्स से बचें। आराम और तरल पदार्थ लें।")
    elif "dose" in msg or "mg/kg" in msg:
        return ("Typical antibiotic dose: 10–20 mg/kg. Adjust according to doctor guidance."
                if ui_lang=="English"
                else "सामान्य एंटीबायोटिक खुराक: 10–20 mg/kg। डॉक्टर की सलाह के अनुसार समायोजित करें।")
    elif "pneumonia" in msg:
        return ("For pneumonia, amoxicillin or azithromycin is usually recommended."
                if ui_lang=="English"
                else "निमोनिया के लिए आमतौर पर एमॉक्सिसिलिन या एजिथ्रोमाइसिन की सिफारिश की जाती है।")
    elif "fever" in msg:
        return ("For fever, monitor temperature and give paracetamol if needed."
                if ui_lang=="English"
                else "बुखार के लिए, तापमान की निगरानी करें और आवश्यक होने पर पैरासिटामॉल दें।")
    elif "help" in msg or "guide" in msg:
        return ("Ask about antibiotic misuse, dosage, or diagnosis guidance."
                if ui_lang=="English"
                else "एंटीबायोटिक दुरुपयोग, खुराक, या निदान मार्गदर्शन के बारे में पूछें।")
    else:
        return ("Sorry, I can only guide on antibiotics, dosage, and basic symptoms."
                if ui_lang=="English"
                else "क्षमा करें, मैं केवल एंटीबायोटिक्स, खुराक और बुनियादी लक्षणों पर मार्गदर्शन कर सकता हूँ।")



